# TODO
services:
  traefik:
    image: "traefik"
    restart: always
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik_data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: |
      bash -c "
      alembic upgrade heads &&
      python -m uvicorn main:app --host 0.0.0.0 --port 8080
      "
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.entrypoints=web
      - traefik.http.routers.web.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.web-secure.entrypoints=websecure
      - traefik.http.routers.web-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.web-secure.tls=true
      - traefik.http.routers.web-secure.service=web
      - traefik.http.routers.web-secure.tls.certresolver=mytlschallenge
      - traefik.http.services.web.loadbalancer.server.port=8080

  directus:
    image: directus/directus:11.12.0
    container_name: directus
    restart: always
    depends_on:
      - db

    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./templates:/directus/templates

    environment:
      - PUBLIC_URL=https://${DIRECTUS_SUBDOMAIN}.${DOMAIN_NAME}
      - SECRET=${SECRET}
      - ADMIN_EMAIL=${SSL_EMAIL}
      - ADMIN_PASSWORD=${PASSWORD_DIRECTUS}
      - DB_CLIENT=${DIRECTUS_DB_CLIENT}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=${DB_PORT}
      - WEBSOCKETS_ENABLED=true
        # далее натсроки для smtp
      #- EMAIL_FROM=${EMAIL_FROM}
      #- EMAIL_TRANSPORT=smtp
      #- EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST}
      #- EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      #- EMAIL_SMTP_USER=${EMAIL_SMTP_USER}
     # - EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}

    labels:
      - traefik.enable=true
      - traefik.http.routers.directus.entrypoints=web
      - traefik.http.routers.directus.rule=Host(`${DIRECTUS_SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.directus-secure.entrypoints=websecure
      - traefik.http.routers.directus-secure.rule=Host(`${DIRECTUS_SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.directus-secure.tls=true
      - traefik.http.routers.directus-secure.service=directus
      - traefik.http.routers.directus-secure.tls.certresolver=mytlschallenge
      - traefik.http.services.directus.loadbalancer.server.port=8055
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    depends_on:
      - db
    ports:
      - "127.0.0.1:5678:5678"
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`${N8N_SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.entrypoints=web,websecure
      - traefik.http.routers.n8n.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.n8n.headers.SSLRedirect=true
      - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
      - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
      - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
      - traefik.http.middlewares.n8n.headers.forceSTSHeader=true
      - traefik.http.middlewares.n8n.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.n8n.headers.STSPreload=true
      - traefik.http.routers.n8n.middlewares=n8n@docker
    environment:
      - N8N_HOST=${N8N_SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${N8N_SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - DB_TYPE=postgresdb
      - DB_TABLE_PREFIX=n8n_
      - DB_POSTGRESDB_DATABASE=${DB_NAME}
      - DB_POSTGRESDB_HOST=${DB_HOST} #Это имя контенера который линкуется, он даже днс создает
      - DB_POSTGRESDB_USER=${DB_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - EXECUTIONS_DATA_MAX_AGE=168 #сколько часов хранить выполнения
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=10000 #колличество выполнений котрое храним
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem #при работе с бинарными данными записывать их на диск
    volumes:
      - ./n8n_data:/home/node/.n8n # где будет наш преокт
      - ./local-files:/files       # папка для локальных файлов
volumes:
  postgres_data: