"""add_index_on_table_subscriptions

Revision ID: 1c77f9b8eba3
Revises: 28aca74488e8
Create Date: 2025-10-16 16:54:40.957415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c77f9b8eba3'
down_revision: Union[str, None] = '28aca74488e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_subscriptions_category_id', 'subscriptions', ['category_id'], unique=False)
    op.create_index('idx_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_subscriptions_user_id', table_name='subscriptions')
    op.drop_index('idx_subscriptions_category_id', table_name='subscriptions')
    # ### end Alembic commands ###
