"""add_index_on_table_vacancies

Revision ID: 28aca74488e8
Revises: b5044e3e8dd5
Create Date: 2025-10-16 15:19:58.690902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28aca74488e8'
down_revision: Union[str, None] = 'b5044e3e8dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vacancies_category_id'), 'vacancies', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancies_category_id'), table_name='vacancies')
    # ### end Alembic commands ###
