"""add_index_on_table_users

Revision ID: b5044e3e8dd5
Revises: e9112a856d5b
Create Date: 2025-10-16 15:12:23.573234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5044e3e8dd5'
down_revision: Union[str, None] = 'e9112a856d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_bot_status'), 'users', ['bot_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_bot_status'), table_name='users')
    # ### end Alembic commands ###
