"""Add Title To Vacancy

Revision ID: e9112a856d5b
Revises: 84d0e81038fd
Create Date: 2025-08-29 17:52:08.459400

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9112a856d5b"
down_revision: Union[str, None] = "84d0e81038fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vacancies", sa.Column("title", sa.String(length=300), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vacancies", "title")
    # ### end Alembic commands ###
