name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install deps
        run: | pip install -r requirements.txt; pip install -r requirements-dev.txt
      - name: Lint
        run: | pytest .